name = "check"
main = "src/index.js"
compatibility_date = "2025-11-30"
keep_vars = true

[[kv_namespaces]]
binding = "ckeck" 
id = "cc8ba39b850b42a78c4bca743e99e483" # 替换成你实际的 KV ID

[triggers]
crons = ["0 1,13 * * *"] # 北京时间 9:00 和 21:00
